package app

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// This file makes a shell launched by resticscope identify itself for its whole
// lifetime, not just in the scroll-away banner: the prompt gets a persistent
// "(resticscope·repo)" prefix, venv-style. A reserved footer line is not
// achievable here - tea.ExecProcess hands the entire terminal to the child, so
// holding a line would need scroll-region escapes that pagers/editors/clear all
// break - which makes the prompt prefix the reliable mechanism. The user's
// dotfiles are never modified; each supported shell is steered through a
// generated, per-session rc that sources the user's own startup file first and
// then installs a guarded precmd hook, so the tag is re-applied even when a
// prompt framework (starship, powerlevel10k, oh-my-posh) rewrites the prompt
// before every cycle. Unsupported shells keep today's banner-only behavior.

// promptTag returns a repository or local-shell prefix. Validated repository
// names require no shell-specific escaping, but generated scripts still quote it.
func promptTag(repoName string) string {
	if repoName == "" {
		return "(resticscope)"
	}
	return "(resticscope·" + repoName + ")"
}

// applyPromptTag configures supported shells by basename and chains temporary
// scaffolding into Cleanup. Failure leaves the session usable but untagged and
// returns an error containing no credential or snapshot path.
func applyPromptTag(s *ShellSession, tag string) error {
	base := filepath.Base(s.Shell)
	switch {
	case base == "bash" || strings.HasPrefix(base, "bash-"):
	case base == "zsh" || strings.HasPrefix(base, "zsh-"):
	case base == "fish" || strings.HasPrefix(base, "fish-"):
	default:
		return nil
	}
	switch {
	case base == "bash" || strings.HasPrefix(base, "bash-"):
		rc, err := writePromptFile("resticscope-bashrc-*", bashPromptRC(tag))
		if err != nil {
			return err
		}
		s.execArgv = []string{s.Shell, "--rcfile", rc, "-i"}
		s.Cleanup = chainCleanup(s.Cleanup, func() error { return os.Remove(rc) })
	case base == "zsh" || strings.HasPrefix(base, "zsh-"):
		var origZDot string
		if v, ok := envLookup(s.Env, "ZDOTDIR"); ok {
			origZDot = v
		}
		dir, err := writeZshPromptDir(tag, origZDot)
		if err != nil {
			return err
		}
		s.promptZDotDir = dir
		s.Cleanup = chainCleanup(s.Cleanup, func() error { return os.RemoveAll(dir) })
	case base == "fish" || strings.HasPrefix(base, "fish-"):
		s.execArgv = []string{s.Shell, "-i", "-C", fishPromptInit(tag)}
	}
	return nil
}

// bashPromptRC sources the user's bashrc before installing the prompt tag.
func bashPromptRC(tag string) string {
	// Mark SGR escapes as zero-width for bash line editing.
	prefix := `\[\e[1;33m\]` + tag + `\[\e[0m\] `
	var b strings.Builder
	b.WriteString("# Generated by resticscope for one launched shell; deleted when it exits.\n")
	b.WriteString("# The user's normal startup file runs first, so this only adds the prompt tag.\n")
	b.WriteString("[ -f \"$HOME/.bashrc\" ] && . \"$HOME/.bashrc\"\n")
	b.WriteString("\n")
	b.WriteString("_resticscope_ps1_tag=" + posixQuote(prefix) + "\n")
	b.WriteString(`_resticscope_tag_prompt() {
  case $PS1 in
    "$_resticscope_ps1_tag"*) ;;
    *) PS1="$_resticscope_ps1_tag$PS1" ;;
  esac
}
`)
	// Append after user hooks so framework rewrites run first. Guard against
	// duplicate tags and preserve scalar and Bash 5.1+ array PROMPT_COMMAND forms.
	b.WriteString(`case "$(declare -p PROMPT_COMMAND 2>/dev/null)" in
  'declare -a'*) PROMPT_COMMAND+=(_resticscope_tag_prompt) ;;
  *) PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND; }_resticscope_tag_prompt" ;;
esac
`)
	return b.String()
}

// zshPromptZshenv forwards to the user's zshenv, records a non-empty ZDOTDIR
// reassignment, and restores the generated directory for later startup files.
func zshPromptZshenv(userDir, ownDir string) string {
	var b strings.Builder
	b.WriteString("# Generated by resticscope for one launched shell; deleted when it exits.\n")
	b.WriteString("# Forwards to the user's real zshenv; only the sibling .zshrc adds the tag.\n")
	fmt.Fprintf(&b, "[ -f %[1]s/.zshenv ] && . %[1]s/.zshenv\n", userDir)
	fmt.Fprintf(&b, `if [ "$ZDOTDIR" != %[1]s ]; then
  _resticscope_user_zdotdir="$ZDOTDIR"
  ZDOTDIR=%[1]s
fi
`, posixQuote(ownDir))
	return b.String()
}

// zshPromptZshrc restores user ZDOTDIR, sources zshrc, then appends the tag hook.
func zshPromptZshrc(tag, userDir string, hadZDotDir bool) string {
	prefix := "%B%F{yellow}" + tag + "%f%b "
	var b strings.Builder
	// User zshenv reassignment wins over the inherited ZDOTDIR during sourcing.
	b.WriteString(`if [ -n "$_resticscope_user_zdotdir" ]; then
  ZDOTDIR="$_resticscope_user_zdotdir"
else
`)
	if hadZDotDir {
		fmt.Fprintf(&b, "  ZDOTDIR=%s\n", userDir)
	} else {
		b.WriteString("  unset ZDOTDIR\n")
	}
	b.WriteString("fi\nunset _resticscope_user_zdotdir\n")
	b.WriteString("[ -f \"${ZDOTDIR:-$HOME}/.zshrc\" ] && . \"${ZDOTDIR:-$HOME}/.zshrc\"\n")
	b.WriteString("\n")
	b.WriteString("_resticscope_prompt_tag=" + posixQuote(prefix) + "\n")
	// Append after framework hooks and guard against duplicate tags.
	b.WriteString(`_resticscope_tag_prompt() {
  [[ $PROMPT == "$_resticscope_prompt_tag"* ]] || PROMPT="$_resticscope_prompt_tag$PROMPT"
}
precmd_functions+=(_resticscope_tag_prompt)
`)
	return b.String()
}

// fishPromptInit wraps the fish_prompt installed by config.fish; fish -C runs
// this initialization afterward without a scaffolding file.
func fishPromptInit(tag string) string {
	return `functions -q fish_prompt; and functions -c fish_prompt _resticscope_orig_prompt
function fish_prompt
    set_color -o yellow
    echo -n ` + posixQuote(tag+" ") + `
    set_color normal
    if functions -q _resticscope_orig_prompt
        _resticscope_orig_prompt
    else
        printf '%s> ' (prompt_pwd)
    end
end`
}

// writePromptFile writes a fresh 0600 generated rc and returns its path. Callers
// supply only static shell code and a non-secret validated prompt tag.
func writePromptFile(pattern, content string) (string, error) {
	f, err := os.CreateTemp("", pattern)
	if err != nil {
		return "", err
	}
	name := f.Name()
	if _, err := f.WriteString(content); err != nil {
		_ = f.Close()
		_ = os.Remove(name)
		return "", err
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(name)
		return "", err
	}
	return name, nil
}

// writeZshPromptDir creates a temporary zshenv and zshrc, falling back to HOME
// when the child has no ZDOTDIR.
func writeZshPromptDir(tag, origZDotDir string) (string, error) {
	userDir := `"$HOME"`
	if origZDotDir != "" {
		userDir = posixQuote(origZDotDir)
	}
	dir, err := os.MkdirTemp("", "resticscope-zdotdir-*")
	if err != nil {
		return "", err
	}
	files := map[string]string{
		".zshenv": zshPromptZshenv(userDir, dir),
		".zshrc":  zshPromptZshrc(tag, userDir, origZDotDir != ""),
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
			_ = os.RemoveAll(dir)
			return "", err
		}
	}
	return dir, nil
}

// chainCleanup composes two cleanup funcs; both always run, errors joined.
func chainCleanup(first, second func() error) func() error {
	return func() error { return errors.Join(first(), second()) }
}

func envLookup(env []string, key string) (string, bool) {
	for _, kv := range env {
		if k, v, ok := strings.Cut(kv, "="); ok && k == key {
			return v, true
		}
	}
	return "", false
}

// envWithout removes every key occurrence before a single replacement is appended.
func envWithout(env []string, key string) []string {
	out := make([]string, 0, len(env))
	for _, kv := range env {
		if k, _, ok := strings.Cut(kv, "="); ok && k == key {
			continue
		}
		out = append(out, kv)
	}
	return out
}
