package app

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// This file makes a shell launched by resticscope identify itself for its whole
// lifetime, not just in the scroll-away banner: the prompt gets a persistent
// "(resticscope·repo)" prefix, venv-style. A reserved footer line is not
// achievable here — tea.ExecProcess hands the entire terminal to the child, so
// holding a line would need scroll-region escapes that pagers/editors/clear all
// break — which makes the prompt prefix the reliable mechanism. The user's
// dotfiles are never modified; each supported shell is steered through a
// generated, per-session rc that sources the user's own startup file first and
// then installs a guarded precmd hook, so the tag is re-applied even when a
// prompt framework (starship, powerlevel10k, oh-my-posh) rewrites the prompt
// before every cycle. Unsupported shells keep today's banner-only behavior.

// promptTag renders the prompt prefix for a repo-scoped shell, or the bare app
// tag for the credential-free local shell when repoName is empty. Repo names
// are validated to [A-Za-z0-9._-] (config.validRepoName), so the tag needs no
// per-shell escaping; the generated scripts still single-quote it defensively.
func promptTag(repoName string) string {
	if repoName == "" {
		return "(resticscope)"
	}
	return "(resticscope·" + repoName + ")"
}

// applyPromptTag arranges for the session's shell to show tag as a persistent
// prompt prefix, dispatching on the shell binary's basename. It may set the
// session's execArgv, record the zsh ZDOTDIR override (surfaced only through
// InteractiveEnv), and chain scaffolding removal onto its Cleanup. Best-effort by design: when writing the throwaway rc fails the
// session is left untagged and the error returned for a log line — a cosmetic
// feature must not block a perfectly working shell. The error carries at most
// a temp-scaffolding path, never a repo credential or snapshot path.
func applyPromptTag(s *ShellSession, tag string) error {
	base := filepath.Base(s.Shell)
	switch {
	case base == "bash" || strings.HasPrefix(base, "bash-"):
	case base == "zsh" || strings.HasPrefix(base, "zsh-"):
	case base == "fish" || strings.HasPrefix(base, "fish-"):
	default:
		return nil
	}
	switch {
	case base == "bash" || strings.HasPrefix(base, "bash-"):
		rc, err := writePromptFile("resticscope-bashrc-*", bashPromptRC(tag))
		if err != nil {
			return err
		}
		s.execArgv = []string{s.Shell, "--rcfile", rc, "-i"}
		s.Cleanup = chainCleanup(s.Cleanup, func() error { return os.Remove(rc) })
	case base == "zsh" || strings.HasPrefix(base, "zsh-"):
		var origZDot string
		if v, ok := envLookup(s.Env, "ZDOTDIR"); ok {
			origZDot = v
		}
		dir, err := writeZshPromptDir(tag, origZDot)
		if err != nil {
			return err
		}
		s.promptZDotDir = dir
		s.Cleanup = chainCleanup(s.Cleanup, func() error { return os.RemoveAll(dir) })
	case base == "fish" || strings.HasPrefix(base, "fish-"):
		s.execArgv = []string{s.Shell, "-i", "-C", fishPromptInit(tag)}
	}
	return nil
}

// bashPromptRC is the --rcfile bash reads instead of ~/.bashrc; it sources the
// real ~/.bashrc first, so the only behavioral delta is the prompt tag.
func bashPromptRC(tag string) string {
	// \[ \] mark the SGR escapes as zero-width so bash's line editing keeps
	// measuring the prompt correctly.
	prefix := `\[\e[1;33m\]` + tag + `\[\e[0m\] `
	var b strings.Builder
	b.WriteString("# Generated by resticscope for one launched shell; deleted when it exits.\n")
	b.WriteString("# The user's normal startup file runs first, so this only adds the prompt tag.\n")
	b.WriteString("[ -f \"$HOME/.bashrc\" ] && . \"$HOME/.bashrc\"\n")
	b.WriteString("\n")
	b.WriteString("_resticscope_ps1_tag=" + posixQuote(prefix) + "\n")
	b.WriteString(`_resticscope_tag_prompt() {
  case $PS1 in
    "$_resticscope_ps1_tag"*) ;;
    *) PS1="$_resticscope_ps1_tag$PS1" ;;
  esac
}
`)
	// The hook is appended after the user rc on purpose: PROMPT_COMMAND entries
	// run in order, so the tag is re-applied after any framework hook that
	// rewrites PS1 each cycle. The case guard keeps a static PS1 from growing a
	// copy of the tag on every prompt. PROMPT_COMMAND may be an array (bash >=
	// 5.1); detect via declare -p so existing hooks are preserved either way.
	b.WriteString(`case "$(declare -p PROMPT_COMMAND 2>/dev/null)" in
  'declare -a'*) PROMPT_COMMAND+=(_resticscope_tag_prompt) ;;
  *) PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND; }_resticscope_tag_prompt" ;;
esac
`)
	return b.String()
}

// zshPromptZshenv is the .zshenv of the throwaway ZDOTDIR. It forwards to the
// user's real zshenv, and when that file reassigns ZDOTDIR (a common dotfile
// layout, `export ZDOTDIR=$HOME/.zsh`) it remembers the user's choice and
// re-points ZDOTDIR at ownDir, so the sibling tag .zshrc still runs. The
// sibling restores the remembered value before sourcing the user's rc from it,
// so the custom layout keeps working.
func zshPromptZshenv(userDir, ownDir string) string {
	var b strings.Builder
	b.WriteString("# Generated by resticscope for one launched shell; deleted when it exits.\n")
	b.WriteString("# Forwards to the user's real zshenv; only the sibling .zshrc adds the tag.\n")
	fmt.Fprintf(&b, "[ -f %[1]s/.zshenv ] && . %[1]s/.zshenv\n", userDir)
	fmt.Fprintf(&b, `if [ "$ZDOTDIR" != %[1]s ]; then
  _resticscope_user_zdotdir="$ZDOTDIR"
  ZDOTDIR=%[1]s
fi
`, posixQuote(ownDir))
	return b.String()
}

// zshPromptZshrc is the .zshrc of the throwaway ZDOTDIR: restore the user's
// ZDOTDIR, run their real zshrc, then hook the tag in as the last precmd.
func zshPromptZshrc(tag, userDir string, hadZDotDir bool) string {
	prefix := "%B%F{yellow}" + tag + "%f%b "
	var b strings.Builder
	// Restore ZDOTDIR before sourcing so anything the user rc reads from it
	// sees the real value, not this temp directory: a reassignment made by the
	// user's zshenv wins, then the value resticscope itself was launched with.
	b.WriteString(`if [ -n "$_resticscope_user_zdotdir" ]; then
  ZDOTDIR="$_resticscope_user_zdotdir"
else
`)
	if hadZDotDir {
		fmt.Fprintf(&b, "  ZDOTDIR=%s\n", userDir)
	} else {
		b.WriteString("  unset ZDOTDIR\n")
	}
	b.WriteString("fi\nunset _resticscope_user_zdotdir\n")
	b.WriteString("[ -f \"${ZDOTDIR:-$HOME}/.zshrc\" ] && . \"${ZDOTDIR:-$HOME}/.zshrc\"\n")
	b.WriteString("\n")
	b.WriteString("_resticscope_prompt_tag=" + posixQuote(prefix) + "\n")
	// precmd_functions run in order before each prompt, after framework hooks
	// added by the user rc have rewritten PROMPT — so the tag survives them.
	// The guard keeps a static PROMPT from accumulating copies.
	b.WriteString(`_resticscope_tag_prompt() {
  [[ $PROMPT == "$_resticscope_prompt_tag"* ]] || PROMPT="$_resticscope_prompt_tag$PROMPT"
}
precmd_functions+=(_resticscope_tag_prompt)
`)
	return b.String()
}

// fishPromptInit is passed via `fish -C`, which runs after config.fish — so it
// wraps whatever fish_prompt the user (or a framework) installed there. No
// scaffolding file is needed.
func fishPromptInit(tag string) string {
	return `functions -q fish_prompt; and functions -c fish_prompt _resticscope_orig_prompt
function fish_prompt
    set_color -o yellow
    echo -n ` + posixQuote(tag+" ") + `
    set_color normal
    if functions -q _resticscope_orig_prompt
        _resticscope_orig_prompt
    else
        printf '%s> ' (prompt_pwd)
    end
end`
}

// writePromptFile persists a generated rc to a fresh 0600 temp file and returns
// its path. The contents carry the repo name (a validated config identifier,
// not a secret) and nothing else — no credentials, no snapshot paths.
func writePromptFile(pattern, content string) (string, error) {
	f, err := os.CreateTemp("", pattern)
	if err != nil {
		return "", err
	}
	name := f.Name()
	if _, err := f.WriteString(content); err != nil {
		f.Close()
		os.Remove(name)
		return "", err
	}
	if err := f.Close(); err != nil {
		os.Remove(name)
		return "", err
	}
	return name, nil
}

// writeZshPromptDir builds the throwaway ZDOTDIR (.zshenv + .zshrc) and returns
// its path. origZDotDir is the ZDOTDIR from the child environment, empty when
// the user has none — then the rc files fall back to "$HOME".
func writeZshPromptDir(tag, origZDotDir string) (string, error) {
	userDir := `"$HOME"`
	if origZDotDir != "" {
		userDir = posixQuote(origZDotDir)
	}
	dir, err := os.MkdirTemp("", "resticscope-zdotdir-*")
	if err != nil {
		return "", err
	}
	files := map[string]string{
		".zshenv": zshPromptZshenv(userDir, dir),
		".zshrc":  zshPromptZshrc(tag, userDir, origZDotDir != ""),
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
			os.RemoveAll(dir)
			return "", err
		}
	}
	return dir, nil
}

// chainCleanup composes two cleanup funcs; both always run, errors joined.
func chainCleanup(first, second func() error) func() error {
	return func() error { return errors.Join(first(), second()) }
}

// envLookup returns the value of key in an os.Environ()-style slice.
func envLookup(env []string, key string) (string, bool) {
	for _, kv := range env {
		if k, v, ok := strings.Cut(kv, "="); ok && k == key {
			return v, true
		}
	}
	return "", false
}

// envWithout returns env with every entry for key removed, so a single
// replacement append can't leave the child with two conflicting values.
func envWithout(env []string, key string) []string {
	out := make([]string, 0, len(env))
	for _, kv := range env {
		if k, _, ok := strings.Cut(kv, "="); ok && k == key {
			continue
		}
		out = append(out, kv)
	}
	return out
}
